spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/scanner-network"
  servlet:
    multipart:
      max-file-size:
        5MB
      max-request-size:
        5MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5470/scanner
    username: postgres
    password: postgres



