spring:
  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5440/scanner
    username: postgres
    password: postgres

